{% set name = "opentelemetry-instrumentation-watsonx" %}
{% set version = "0.51.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_watsonx-{{ version }}.tar.gz
  sha256: 50a808f3cf918d35bd0d98edd03be92bdd214934b3cbc12af4e5f063bc5ff1dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5

test:
  imports:
    - opentelemetry.instrumentation.watsonx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry IBM Watsonx Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
